/*
 * Fanapium Core API
 * Fanapium B2B2C services
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.springframework.social.fanapium.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * AttributeTemplateSrv
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-02T09:35:11.370+04:30")
public class AttributeTemplateSrv {
    @JsonProperty("name")
    private String name = null;

    @JsonProperty("code")
    private String code = null;

    @JsonProperty("attributes")
    private List<AttributeSrv> attributes = null;

    public AttributeTemplateSrv name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public AttributeTemplateSrv code(String code) {
        this.code = code;
        return this;
    }

    /**
     * Get code
     *
     * @return code
     **/

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public AttributeTemplateSrv attributes(List<AttributeSrv> attributes) {
        this.attributes = attributes;
        return this;
    }

    public AttributeTemplateSrv addAttributesItem(AttributeSrv attributesItem) {
        if (this.attributes == null) {
            this.attributes = new ArrayList<AttributeSrv>();
        }
        this.attributes.add(attributesItem);
        return this;
    }

    /**
     * Get attributes
     *
     * @return attributes
     **/

    public List<AttributeSrv> getAttributes() {
        return attributes;
    }

    public void setAttributes(List<AttributeSrv> attributes) {
        this.attributes = attributes;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AttributeTemplateSrv attributeTemplateSrv = (AttributeTemplateSrv) o;
        return Objects.equals(this.name, attributeTemplateSrv.name) &&
                Objects.equals(this.code, attributeTemplateSrv.code) &&
                Objects.equals(this.attributes, attributeTemplateSrv.attributes);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, code, attributes);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AttributeTemplateSrv {\n");

        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    code: ").append(toIndentedString(code)).append("\n");
        sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

