/*
 * Fanapium Core API
 * Fanapium B2B2C services
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.springframework.social.fanapium.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * AwardSrv
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-02T09:35:11.370+04:30")
public class AwardSrv {
    @JsonProperty("id")
    private Long id = null;

    @JsonProperty("description")
    private String description = null;

    @JsonProperty("value")
    private Double value = null;

    @JsonProperty("count")
    private Integer count = null;

    @JsonProperty("userSrvs")
    private List<UserSrv> userSrvs = null;

    @JsonProperty("userCount")
    private Long userCount = null;

    @JsonProperty("cash")
    private Boolean cash = null;

    public AwardSrv id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public AwardSrv description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get description
     *
     * @return description
     **/

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public AwardSrv value(Double value) {
        this.value = value;
        return this;
    }

    /**
     * Get value
     *
     * @return value
     **/

    public Double getValue() {
        return value;
    }

    public void setValue(Double value) {
        this.value = value;
    }

    public AwardSrv count(Integer count) {
        this.count = count;
        return this;
    }

    /**
     * Get count
     *
     * @return count
     **/

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public AwardSrv userSrvs(List<UserSrv> userSrvs) {
        this.userSrvs = userSrvs;
        return this;
    }

    public AwardSrv addUserSrvsItem(UserSrv userSrvsItem) {
        if (this.userSrvs == null) {
            this.userSrvs = new ArrayList<UserSrv>();
        }
        this.userSrvs.add(userSrvsItem);
        return this;
    }

    /**
     * Get userSrvs
     *
     * @return userSrvs
     **/

    public List<UserSrv> getUserSrvs() {
        return userSrvs;
    }

    public void setUserSrvs(List<UserSrv> userSrvs) {
        this.userSrvs = userSrvs;
    }

    public AwardSrv userCount(Long userCount) {
        this.userCount = userCount;
        return this;
    }

    /**
     * Get userCount
     *
     * @return userCount
     **/

    public Long getUserCount() {
        return userCount;
    }

    public void setUserCount(Long userCount) {
        this.userCount = userCount;
    }

    public AwardSrv cash(Boolean cash) {
        this.cash = cash;
        return this;
    }

    /**
     * Get cash
     *
     * @return cash
     **/

    public Boolean isCash() {
        return cash;
    }

    public void setCash(Boolean cash) {
        this.cash = cash;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AwardSrv awardSrv = (AwardSrv) o;
        return Objects.equals(this.id, awardSrv.id) &&
                Objects.equals(this.description, awardSrv.description) &&
                Objects.equals(this.value, awardSrv.value) &&
                Objects.equals(this.count, awardSrv.count) &&
                Objects.equals(this.userSrvs, awardSrv.userSrvs) &&
                Objects.equals(this.userCount, awardSrv.userCount) &&
                Objects.equals(this.cash, awardSrv.cash);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, description, value, count, userSrvs, userCount, cash);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AwardSrv {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    value: ").append(toIndentedString(value)).append("\n");
        sb.append("    count: ").append(toIndentedString(count)).append("\n");
        sb.append("    userSrvs: ").append(toIndentedString(userSrvs)).append("\n");
        sb.append("    userCount: ").append(toIndentedString(userCount)).append("\n");
        sb.append("    cash: ").append(toIndentedString(cash)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

