/*
 * Fanapium Core API
 * Fanapium B2B2C services
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.springframework.social.fanapium.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;

/**
 * BusinessSoftSrv
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-02T09:35:11.370+04:30")
public class BusinessSoftSrv {
    @JsonProperty("id")
    private Long id = null;

    @JsonProperty("name")
    private String name = null;

    @JsonProperty("imageInfo")
    private ImageInfoSrv imageInfo = null;

    @JsonProperty("image")
    private String image = null;

    @JsonProperty("numOfProducts")
    private Integer numOfProducts = null;

    @JsonProperty("rate")
    private RateSrv rate = null;

    public BusinessSoftSrv id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public BusinessSoftSrv name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public BusinessSoftSrv imageInfo(ImageInfoSrv imageInfo) {
        this.imageInfo = imageInfo;
        return this;
    }

    /**
     * Get imageInfo
     *
     * @return imageInfo
     **/

    public ImageInfoSrv getImageInfo() {
        return imageInfo;
    }

    public void setImageInfo(ImageInfoSrv imageInfo) {
        this.imageInfo = imageInfo;
    }

    public BusinessSoftSrv image(String image) {
        this.image = image;
        return this;
    }

    /**
     * Get image
     *
     * @return image
     **/

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public BusinessSoftSrv numOfProducts(Integer numOfProducts) {
        this.numOfProducts = numOfProducts;
        return this;
    }

    /**
     * Get numOfProducts
     *
     * @return numOfProducts
     **/

    public Integer getNumOfProducts() {
        return numOfProducts;
    }

    public void setNumOfProducts(Integer numOfProducts) {
        this.numOfProducts = numOfProducts;
    }

    public BusinessSoftSrv rate(RateSrv rate) {
        this.rate = rate;
        return this;
    }

    /**
     * Get rate
     *
     * @return rate
     **/

    public RateSrv getRate() {
        return rate;
    }

    public void setRate(RateSrv rate) {
        this.rate = rate;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BusinessSoftSrv businessSoftSrv = (BusinessSoftSrv) o;
        return Objects.equals(this.id, businessSoftSrv.id) &&
                Objects.equals(this.name, businessSoftSrv.name) &&
                Objects.equals(this.imageInfo, businessSoftSrv.imageInfo) &&
                Objects.equals(this.image, businessSoftSrv.image) &&
                Objects.equals(this.numOfProducts, businessSoftSrv.numOfProducts) &&
                Objects.equals(this.rate, businessSoftSrv.rate);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, imageInfo, image, numOfProducts, rate);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class BusinessSoftSrv {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    imageInfo: ").append(toIndentedString(imageInfo)).append("\n");
        sb.append("    image: ").append(toIndentedString(image)).append("\n");
        sb.append("    numOfProducts: ").append(toIndentedString(numOfProducts)).append("\n");
        sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

