/*
 * Fanapium Core API
 * Fanapium B2B2C services
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.springframework.social.fanapium.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * CompetitionSrv
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-02T09:35:11.370+04:30")
public class CompetitionSrv {
    @JsonProperty("id")
    private Long id = null;

    @JsonProperty("timelineId")
    private Long timelineId = null;

    @JsonProperty("entityId")
    private Long entityId = null;

    @JsonProperty("numOfLikes")
    private Integer numOfLikes = null;

    @JsonProperty("numOfFavorites")
    private Integer numOfFavorites = null;

    @JsonProperty("numOfComments")
    private Integer numOfComments = null;

    @JsonProperty("timestamp")
    private Long timestamp = null;

    @JsonProperty("enable")
    private Boolean enable = null;

    @JsonProperty("hide")
    private Boolean hide = null;

    @JsonProperty("business")
    private BusinessSoftSrv business = null;

    @JsonProperty("userPostInfo")
    private UserPostInfoSrv userPostInfo = null;

    @JsonProperty("metadata")
    private String metadata = null;

    @JsonProperty("latitude")
    private Double latitude = null;

    @JsonProperty("longitude")
    private Double longitude = null;

    @JsonProperty("canComment")
    private Boolean canComment = null;

    @JsonProperty("canLike")
    private Boolean canLike = null;

    @JsonProperty("tags")
    private List<String> tags = null;

    @JsonProperty("type")
    private String type = null;

    @JsonProperty("text")
    private String text = null;

    @JsonProperty("open")
    private Boolean open = null;

    @JsonProperty("confirmed")
    private Boolean confirmed = null;

    @JsonProperty("answerList")
    private List<AnswerSrv> answerList = null;

    @JsonProperty("startDate")
    private Long startDate = null;

    @JsonProperty("endDate")
    private Long endDate = null;

    @JsonProperty("subscriptionCount")
    private Integer subscriptionCount = null;

    @JsonProperty("correctAnswerIndex")
    private Integer correctAnswerIndex = null;

    @JsonProperty("awardSrvs")
    private List<AwardSrv> awardSrvs = null;

    @JsonProperty("awardCount")
    private Long awardCount = null;

    @JsonProperty("awardUserCount")
    private Long awardUserCount = null;

    @JsonProperty("lotteryId")
    private Long lotteryId = null;

    @JsonProperty("selected")
    private Integer selected = null;

    @JsonProperty("guildSrv")
    private GuildSrv guildSrv = null;

    @JsonProperty("costAmount")
    private Double costAmount = null;

    @JsonProperty("blockAmount")
    private Double blockAmount = null;

    @JsonProperty("done")
    private Boolean done = null;

    @JsonProperty("canceled")
    private Boolean canceled = null;

    @JsonProperty("currency")
    private CurrencySrv currency = null;

    public CompetitionSrv id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public CompetitionSrv timelineId(Long timelineId) {
        this.timelineId = timelineId;
        return this;
    }

    /**
     * Get timelineId
     *
     * @return timelineId
     **/

    public Long getTimelineId() {
        return timelineId;
    }

    public void setTimelineId(Long timelineId) {
        this.timelineId = timelineId;
    }

    public CompetitionSrv entityId(Long entityId) {
        this.entityId = entityId;
        return this;
    }

    /**
     * Get entityId
     *
     * @return entityId
     **/

    public Long getEntityId() {
        return entityId;
    }

    public void setEntityId(Long entityId) {
        this.entityId = entityId;
    }

    public CompetitionSrv numOfLikes(Integer numOfLikes) {
        this.numOfLikes = numOfLikes;
        return this;
    }

    /**
     * Get numOfLikes
     *
     * @return numOfLikes
     **/

    public Integer getNumOfLikes() {
        return numOfLikes;
    }

    public void setNumOfLikes(Integer numOfLikes) {
        this.numOfLikes = numOfLikes;
    }

    public CompetitionSrv numOfFavorites(Integer numOfFavorites) {
        this.numOfFavorites = numOfFavorites;
        return this;
    }

    /**
     * Get numOfFavorites
     *
     * @return numOfFavorites
     **/

    public Integer getNumOfFavorites() {
        return numOfFavorites;
    }

    public void setNumOfFavorites(Integer numOfFavorites) {
        this.numOfFavorites = numOfFavorites;
    }

    public CompetitionSrv numOfComments(Integer numOfComments) {
        this.numOfComments = numOfComments;
        return this;
    }

    /**
     * Get numOfComments
     *
     * @return numOfComments
     **/

    public Integer getNumOfComments() {
        return numOfComments;
    }

    public void setNumOfComments(Integer numOfComments) {
        this.numOfComments = numOfComments;
    }

    public CompetitionSrv timestamp(Long timestamp) {
        this.timestamp = timestamp;
        return this;
    }

    /**
     * Get timestamp
     *
     * @return timestamp
     **/

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    public CompetitionSrv enable(Boolean enable) {
        this.enable = enable;
        return this;
    }

    /**
     * Get enable
     *
     * @return enable
     **/

    public Boolean isEnable() {
        return enable;
    }

    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    public CompetitionSrv hide(Boolean hide) {
        this.hide = hide;
        return this;
    }

    /**
     * Get hide
     *
     * @return hide
     **/

    public Boolean isHide() {
        return hide;
    }

    public void setHide(Boolean hide) {
        this.hide = hide;
    }

    public CompetitionSrv business(BusinessSoftSrv business) {
        this.business = business;
        return this;
    }

    /**
     * Get business
     *
     * @return business
     **/

    public BusinessSoftSrv getBusiness() {
        return business;
    }

    public void setBusiness(BusinessSoftSrv business) {
        this.business = business;
    }

    public CompetitionSrv userPostInfo(UserPostInfoSrv userPostInfo) {
        this.userPostInfo = userPostInfo;
        return this;
    }

    /**
     * Get userPostInfo
     *
     * @return userPostInfo
     **/

    public UserPostInfoSrv getUserPostInfo() {
        return userPostInfo;
    }

    public void setUserPostInfo(UserPostInfoSrv userPostInfo) {
        this.userPostInfo = userPostInfo;
    }

    public CompetitionSrv metadata(String metadata) {
        this.metadata = metadata;
        return this;
    }

    /**
     * Get metadata
     *
     * @return metadata
     **/

    public String getMetadata() {
        return metadata;
    }

    public void setMetadata(String metadata) {
        this.metadata = metadata;
    }

    public CompetitionSrv latitude(Double latitude) {
        this.latitude = latitude;
        return this;
    }

    /**
     * Get latitude
     *
     * @return latitude
     **/

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public CompetitionSrv longitude(Double longitude) {
        this.longitude = longitude;
        return this;
    }

    /**
     * Get longitude
     *
     * @return longitude
     **/

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public CompetitionSrv canComment(Boolean canComment) {
        this.canComment = canComment;
        return this;
    }

    /**
     * Get canComment
     *
     * @return canComment
     **/

    public Boolean isCanComment() {
        return canComment;
    }

    public void setCanComment(Boolean canComment) {
        this.canComment = canComment;
    }

    public CompetitionSrv canLike(Boolean canLike) {
        this.canLike = canLike;
        return this;
    }

    /**
     * Get canLike
     *
     * @return canLike
     **/

    public Boolean isCanLike() {
        return canLike;
    }

    public void setCanLike(Boolean canLike) {
        this.canLike = canLike;
    }

    public CompetitionSrv tags(List<String> tags) {
        this.tags = tags;
        return this;
    }

    public CompetitionSrv addTagsItem(String tagsItem) {
        if (this.tags == null) {
            this.tags = new ArrayList<String>();
        }
        this.tags.add(tagsItem);
        return this;
    }

    /**
     * Get tags
     *
     * @return tags
     **/

    public List<String> getTags() {
        return tags;
    }

    public void setTags(List<String> tags) {
        this.tags = tags;
    }

    public CompetitionSrv type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     **/

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public CompetitionSrv text(String text) {
        this.text = text;
        return this;
    }

    /**
     * Get text
     *
     * @return text
     **/

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public CompetitionSrv open(Boolean open) {
        this.open = open;
        return this;
    }

    /**
     * Get open
     *
     * @return open
     **/

    public Boolean isOpen() {
        return open;
    }

    public void setOpen(Boolean open) {
        this.open = open;
    }

    public CompetitionSrv confirmed(Boolean confirmed) {
        this.confirmed = confirmed;
        return this;
    }

    /**
     * Get confirmed
     *
     * @return confirmed
     **/

    public Boolean isConfirmed() {
        return confirmed;
    }

    public void setConfirmed(Boolean confirmed) {
        this.confirmed = confirmed;
    }

    public CompetitionSrv answerList(List<AnswerSrv> answerList) {
        this.answerList = answerList;
        return this;
    }

    public CompetitionSrv addAnswerListItem(AnswerSrv answerListItem) {
        if (this.answerList == null) {
            this.answerList = new ArrayList<AnswerSrv>();
        }
        this.answerList.add(answerListItem);
        return this;
    }

    /**
     * Get answerList
     *
     * @return answerList
     **/

    public List<AnswerSrv> getAnswerList() {
        return answerList;
    }

    public void setAnswerList(List<AnswerSrv> answerList) {
        this.answerList = answerList;
    }

    public CompetitionSrv startDate(Long startDate) {
        this.startDate = startDate;
        return this;
    }

    /**
     * Get startDate
     *
     * @return startDate
     **/

    public Long getStartDate() {
        return startDate;
    }

    public void setStartDate(Long startDate) {
        this.startDate = startDate;
    }

    public CompetitionSrv endDate(Long endDate) {
        this.endDate = endDate;
        return this;
    }

    /**
     * Get endDate
     *
     * @return endDate
     **/

    public Long getEndDate() {
        return endDate;
    }

    public void setEndDate(Long endDate) {
        this.endDate = endDate;
    }

    public CompetitionSrv subscriptionCount(Integer subscriptionCount) {
        this.subscriptionCount = subscriptionCount;
        return this;
    }

    /**
     * Get subscriptionCount
     *
     * @return subscriptionCount
     **/

    public Integer getSubscriptionCount() {
        return subscriptionCount;
    }

    public void setSubscriptionCount(Integer subscriptionCount) {
        this.subscriptionCount = subscriptionCount;
    }

    public CompetitionSrv correctAnswerIndex(Integer correctAnswerIndex) {
        this.correctAnswerIndex = correctAnswerIndex;
        return this;
    }

    /**
     * Get correctAnswerIndex
     *
     * @return correctAnswerIndex
     **/

    public Integer getCorrectAnswerIndex() {
        return correctAnswerIndex;
    }

    public void setCorrectAnswerIndex(Integer correctAnswerIndex) {
        this.correctAnswerIndex = correctAnswerIndex;
    }

    public CompetitionSrv awardSrvs(List<AwardSrv> awardSrvs) {
        this.awardSrvs = awardSrvs;
        return this;
    }

    public CompetitionSrv addAwardSrvsItem(AwardSrv awardSrvsItem) {
        if (this.awardSrvs == null) {
            this.awardSrvs = new ArrayList<AwardSrv>();
        }
        this.awardSrvs.add(awardSrvsItem);
        return this;
    }

    /**
     * Get awardSrvs
     *
     * @return awardSrvs
     **/

    public List<AwardSrv> getAwardSrvs() {
        return awardSrvs;
    }

    public void setAwardSrvs(List<AwardSrv> awardSrvs) {
        this.awardSrvs = awardSrvs;
    }

    public CompetitionSrv awardCount(Long awardCount) {
        this.awardCount = awardCount;
        return this;
    }

    /**
     * Get awardCount
     *
     * @return awardCount
     **/

    public Long getAwardCount() {
        return awardCount;
    }

    public void setAwardCount(Long awardCount) {
        this.awardCount = awardCount;
    }

    public CompetitionSrv awardUserCount(Long awardUserCount) {
        this.awardUserCount = awardUserCount;
        return this;
    }

    /**
     * Get awardUserCount
     *
     * @return awardUserCount
     **/

    public Long getAwardUserCount() {
        return awardUserCount;
    }

    public void setAwardUserCount(Long awardUserCount) {
        this.awardUserCount = awardUserCount;
    }

    public CompetitionSrv lotteryId(Long lotteryId) {
        this.lotteryId = lotteryId;
        return this;
    }

    /**
     * Get lotteryId
     *
     * @return lotteryId
     **/

    public Long getLotteryId() {
        return lotteryId;
    }

    public void setLotteryId(Long lotteryId) {
        this.lotteryId = lotteryId;
    }

    public CompetitionSrv selected(Integer selected) {
        this.selected = selected;
        return this;
    }

    /**
     * Get selected
     *
     * @return selected
     **/

    public Integer getSelected() {
        return selected;
    }

    public void setSelected(Integer selected) {
        this.selected = selected;
    }

    public CompetitionSrv guildSrv(GuildSrv guildSrv) {
        this.guildSrv = guildSrv;
        return this;
    }

    /**
     * Get guildSrv
     *
     * @return guildSrv
     **/

    public GuildSrv getGuildSrv() {
        return guildSrv;
    }

    public void setGuildSrv(GuildSrv guildSrv) {
        this.guildSrv = guildSrv;
    }

    public CompetitionSrv costAmount(Double costAmount) {
        this.costAmount = costAmount;
        return this;
    }

    /**
     * Get costAmount
     *
     * @return costAmount
     **/

    public Double getCostAmount() {
        return costAmount;
    }

    public void setCostAmount(Double costAmount) {
        this.costAmount = costAmount;
    }

    public CompetitionSrv blockAmount(Double blockAmount) {
        this.blockAmount = blockAmount;
        return this;
    }

    /**
     * Get blockAmount
     *
     * @return blockAmount
     **/

    public Double getBlockAmount() {
        return blockAmount;
    }

    public void setBlockAmount(Double blockAmount) {
        this.blockAmount = blockAmount;
    }

    public CompetitionSrv done(Boolean done) {
        this.done = done;
        return this;
    }

    /**
     * Get done
     *
     * @return done
     **/

    public Boolean isDone() {
        return done;
    }

    public void setDone(Boolean done) {
        this.done = done;
    }

    public CompetitionSrv canceled(Boolean canceled) {
        this.canceled = canceled;
        return this;
    }

    /**
     * Get canceled
     *
     * @return canceled
     **/

    public Boolean isCanceled() {
        return canceled;
    }

    public void setCanceled(Boolean canceled) {
        this.canceled = canceled;
    }

    public CompetitionSrv currency(CurrencySrv currency) {
        this.currency = currency;
        return this;
    }

    /**
     * Get currency
     *
     * @return currency
     **/

    public CurrencySrv getCurrency() {
        return currency;
    }

    public void setCurrency(CurrencySrv currency) {
        this.currency = currency;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CompetitionSrv competitionSrv = (CompetitionSrv) o;
        return Objects.equals(this.id, competitionSrv.id) &&
                Objects.equals(this.timelineId, competitionSrv.timelineId) &&
                Objects.equals(this.entityId, competitionSrv.entityId) &&
                Objects.equals(this.numOfLikes, competitionSrv.numOfLikes) &&
                Objects.equals(this.numOfFavorites, competitionSrv.numOfFavorites) &&
                Objects.equals(this.numOfComments, competitionSrv.numOfComments) &&
                Objects.equals(this.timestamp, competitionSrv.timestamp) &&
                Objects.equals(this.enable, competitionSrv.enable) &&
                Objects.equals(this.hide, competitionSrv.hide) &&
                Objects.equals(this.business, competitionSrv.business) &&
                Objects.equals(this.userPostInfo, competitionSrv.userPostInfo) &&
                Objects.equals(this.metadata, competitionSrv.metadata) &&
                Objects.equals(this.latitude, competitionSrv.latitude) &&
                Objects.equals(this.longitude, competitionSrv.longitude) &&
                Objects.equals(this.canComment, competitionSrv.canComment) &&
                Objects.equals(this.canLike, competitionSrv.canLike) &&
                Objects.equals(this.tags, competitionSrv.tags) &&
                Objects.equals(this.type, competitionSrv.type) &&
                Objects.equals(this.text, competitionSrv.text) &&
                Objects.equals(this.open, competitionSrv.open) &&
                Objects.equals(this.confirmed, competitionSrv.confirmed) &&
                Objects.equals(this.answerList, competitionSrv.answerList) &&
                Objects.equals(this.startDate, competitionSrv.startDate) &&
                Objects.equals(this.endDate, competitionSrv.endDate) &&
                Objects.equals(this.subscriptionCount, competitionSrv.subscriptionCount) &&
                Objects.equals(this.correctAnswerIndex, competitionSrv.correctAnswerIndex) &&
                Objects.equals(this.awardSrvs, competitionSrv.awardSrvs) &&
                Objects.equals(this.awardCount, competitionSrv.awardCount) &&
                Objects.equals(this.awardUserCount, competitionSrv.awardUserCount) &&
                Objects.equals(this.lotteryId, competitionSrv.lotteryId) &&
                Objects.equals(this.selected, competitionSrv.selected) &&
                Objects.equals(this.guildSrv, competitionSrv.guildSrv) &&
                Objects.equals(this.costAmount, competitionSrv.costAmount) &&
                Objects.equals(this.blockAmount, competitionSrv.blockAmount) &&
                Objects.equals(this.done, competitionSrv.done) &&
                Objects.equals(this.canceled, competitionSrv.canceled) &&
                Objects.equals(this.currency, competitionSrv.currency);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, timelineId, entityId, numOfLikes, numOfFavorites, numOfComments, timestamp, enable, hide, business, userPostInfo, metadata, latitude, longitude, canComment, canLike, tags, type, text, open, confirmed, answerList, startDate, endDate, subscriptionCount, correctAnswerIndex, awardSrvs, awardCount, awardUserCount, lotteryId, selected, guildSrv, costAmount, blockAmount, done, canceled, currency);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CompetitionSrv {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    timelineId: ").append(toIndentedString(timelineId)).append("\n");
        sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
        sb.append("    numOfLikes: ").append(toIndentedString(numOfLikes)).append("\n");
        sb.append("    numOfFavorites: ").append(toIndentedString(numOfFavorites)).append("\n");
        sb.append("    numOfComments: ").append(toIndentedString(numOfComments)).append("\n");
        sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
        sb.append("    enable: ").append(toIndentedString(enable)).append("\n");
        sb.append("    hide: ").append(toIndentedString(hide)).append("\n");
        sb.append("    business: ").append(toIndentedString(business)).append("\n");
        sb.append("    userPostInfo: ").append(toIndentedString(userPostInfo)).append("\n");
        sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
        sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
        sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
        sb.append("    canComment: ").append(toIndentedString(canComment)).append("\n");
        sb.append("    canLike: ").append(toIndentedString(canLike)).append("\n");
        sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    text: ").append(toIndentedString(text)).append("\n");
        sb.append("    open: ").append(toIndentedString(open)).append("\n");
        sb.append("    confirmed: ").append(toIndentedString(confirmed)).append("\n");
        sb.append("    answerList: ").append(toIndentedString(answerList)).append("\n");
        sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
        sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
        sb.append("    subscriptionCount: ").append(toIndentedString(subscriptionCount)).append("\n");
        sb.append("    correctAnswerIndex: ").append(toIndentedString(correctAnswerIndex)).append("\n");
        sb.append("    awardSrvs: ").append(toIndentedString(awardSrvs)).append("\n");
        sb.append("    awardCount: ").append(toIndentedString(awardCount)).append("\n");
        sb.append("    awardUserCount: ").append(toIndentedString(awardUserCount)).append("\n");
        sb.append("    lotteryId: ").append(toIndentedString(lotteryId)).append("\n");
        sb.append("    selected: ").append(toIndentedString(selected)).append("\n");
        sb.append("    guildSrv: ").append(toIndentedString(guildSrv)).append("\n");
        sb.append("    costAmount: ").append(toIndentedString(costAmount)).append("\n");
        sb.append("    blockAmount: ").append(toIndentedString(blockAmount)).append("\n");
        sb.append("    done: ").append(toIndentedString(done)).append("\n");
        sb.append("    canceled: ").append(toIndentedString(canceled)).append("\n");
        sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

