/*
 * Fanapium Core API
 * Fanapium B2B2C services
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.springframework.social.fanapium.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;

/**
 * CustomerAmountSrv
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-02T09:35:11.370+04:30")
public class CustomerAmountSrv {
    @JsonProperty("amount")
    private Double amount = null;

    @JsonProperty("currencySrv")
    private CurrencySrv currencySrv = null;

    public CustomerAmountSrv amount(Double amount) {
        this.amount = amount;
        return this;
    }

    /**
     * Get amount
     *
     * @return amount
     **/

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public CustomerAmountSrv currencySrv(CurrencySrv currencySrv) {
        this.currencySrv = currencySrv;
        return this;
    }

    /**
     * Get currencySrv
     *
     * @return currencySrv
     **/

    public CurrencySrv getCurrencySrv() {
        return currencySrv;
    }

    public void setCurrencySrv(CurrencySrv currencySrv) {
        this.currencySrv = currencySrv;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CustomerAmountSrv customerAmountSrv = (CustomerAmountSrv) o;
        return Objects.equals(this.amount, customerAmountSrv.amount) &&
                Objects.equals(this.currencySrv, customerAmountSrv.currencySrv);
    }

    @Override
    public int hashCode() {
        return Objects.hash(amount, currencySrv);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CustomerAmountSrv {\n");

        sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
        sb.append("    currencySrv: ").append(toIndentedString(currencySrv)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

