/*
 * Fanapium Core API
 * Fanapium B2B2C services
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.springframework.social.fanapium.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;

/**
 * ImageInfoSrv
 */
public class ImageInfoSrv {
    @JsonProperty("id")
    private Long id = null;

    @JsonProperty("name")
    private String name = null;

    @JsonProperty("hashCode")
    private String hashCode = null;

    @JsonProperty("description")
    private String description = null;

    @JsonProperty("actualWidth")
    private Integer actualWidth = null;

    @JsonProperty("actualHeight")
    private Integer actualHeight = null;

    @JsonProperty("width")
    private Integer width = null;

    @JsonProperty("height")
    private Integer height = null;

    public ImageInfoSrv id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public ImageInfoSrv name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public ImageInfoSrv hashCode(String hashCode) {
        this.hashCode = hashCode;
        return this;
    }

    /**
     * Get hashCode
     *
     * @return hashCode
     **/

    public String getHashCode() {
        return hashCode;
    }

    public void setHashCode(String hashCode) {
        this.hashCode = hashCode;
    }

    public ImageInfoSrv description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get description
     *
     * @return description
     **/

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public ImageInfoSrv actualWidth(Integer actualWidth) {
        this.actualWidth = actualWidth;
        return this;
    }

    /**
     * Get actualWidth
     *
     * @return actualWidth
     **/

    public Integer getActualWidth() {
        return actualWidth;
    }

    public void setActualWidth(Integer actualWidth) {
        this.actualWidth = actualWidth;
    }

    public ImageInfoSrv actualHeight(Integer actualHeight) {
        this.actualHeight = actualHeight;
        return this;
    }

    /**
     * Get actualHeight
     *
     * @return actualHeight
     **/

    public Integer getActualHeight() {
        return actualHeight;
    }

    public void setActualHeight(Integer actualHeight) {
        this.actualHeight = actualHeight;
    }

    public ImageInfoSrv width(Integer width) {
        this.width = width;
        return this;
    }

    /**
     * Get width
     *
     * @return width
     **/

    public Integer getWidth() {
        return width;
    }

    public void setWidth(Integer width) {
        this.width = width;
    }

    public ImageInfoSrv height(Integer height) {
        this.height = height;
        return this;
    }

    /**
     * Get height
     *
     * @return height
     **/

    public Integer getHeight() {
        return height;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ImageInfoSrv imageInfoSrv = (ImageInfoSrv) o;
        return Objects.equals(this.id, imageInfoSrv.id) &&
                Objects.equals(this.name, imageInfoSrv.name) &&
                Objects.equals(this.hashCode, imageInfoSrv.hashCode) &&
                Objects.equals(this.description, imageInfoSrv.description) &&
                Objects.equals(this.actualWidth, imageInfoSrv.actualWidth) &&
                Objects.equals(this.actualHeight, imageInfoSrv.actualHeight) &&
                Objects.equals(this.width, imageInfoSrv.width) &&
                Objects.equals(this.height, imageInfoSrv.height);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, hashCode, description, actualWidth, actualHeight, width, height);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ImageInfoSrv {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    hashCode: ").append(toIndentedString(hashCode)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    actualWidth: ").append(toIndentedString(actualWidth)).append("\n");
        sb.append("    actualHeight: ").append(toIndentedString(actualHeight)).append("\n");
        sb.append("    width: ").append(toIndentedString(width)).append("\n");
        sb.append("    height: ").append(toIndentedString(height)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

