/*
 * Fanapium Core API
 * Fanapium B2B2C services
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.springframework.social.fanapium.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * InvoiceSrv
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-02T09:35:11.370+04:30")
public class InvoiceSrv {
    @JsonProperty("id")
    private Long id = null;

    @JsonProperty("totalAmount")
    private Long totalAmount = null;

    @JsonProperty("payableAmount")
    private Long payableAmount = null;

    @JsonProperty("vat")
    private Long vat = null;

    @JsonProperty("issuanceDate")
    private Long issuanceDate = null;

    @JsonProperty("deliveryDate")
    private Long deliveryDate = null;

    @JsonProperty("billNumber")
    private String billNumber = null;

    @JsonProperty("issuancePersianDate")
    private String issuancePersianDate = null;

    @JsonProperty("paymentBillNumber")
    private String paymentBillNumber = null;

    @JsonProperty("transactionReferenceId")
    private String transactionReferenceId = null;

    @JsonProperty("uniqueNumber")
    private String uniqueNumber = null;

    @JsonProperty("description")
    private String description = null;

    @JsonProperty("paymentDate")
    private Long paymentDate = null;

    @JsonProperty("payed")
    private Boolean payed = null;

    @JsonProperty("canceled")
    private Boolean canceled = null;

    @JsonProperty("cancelDate")
    private Long cancelDate = null;

    @JsonProperty("business")
    private BusinessSoftSrv business = null;

    @JsonProperty("invoiceItemSrvs")
    private List<InvoiceItemSrv> invoiceItemSrvs = null;

    @JsonProperty("guildSrv")
    private GuildSrv guildSrv = null;

    @JsonProperty("addressSrv")
    private AddressSrv addressSrv = null;

    @JsonProperty("userSrv")
    private UserSrv userSrv = null;

    @JsonProperty("phoneNumber")
    private String phoneNumber = null;

    @JsonProperty("cellphoneNumber")
    private String cellphoneNumber = null;

    @JsonProperty("closed")
    private Boolean closed = null;

    public InvoiceSrv id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public InvoiceSrv totalAmount(Long totalAmount) {
        this.totalAmount = totalAmount;
        return this;
    }

    /**
     * Get totalAmount
     *
     * @return totalAmount
     **/

    public Long getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(Long totalAmount) {
        this.totalAmount = totalAmount;
    }

    public InvoiceSrv payableAmount(Long payableAmount) {
        this.payableAmount = payableAmount;
        return this;
    }

    /**
     * Get payableAmount
     *
     * @return payableAmount
     **/

    public Long getPayableAmount() {
        return payableAmount;
    }

    public void setPayableAmount(Long payableAmount) {
        this.payableAmount = payableAmount;
    }

    public InvoiceSrv vat(Long vat) {
        this.vat = vat;
        return this;
    }

    /**
     * Get vat
     *
     * @return vat
     **/

    public Long getVat() {
        return vat;
    }

    public void setVat(Long vat) {
        this.vat = vat;
    }

    public InvoiceSrv issuanceDate(Long issuanceDate) {
        this.issuanceDate = issuanceDate;
        return this;
    }

    /**
     * Get issuanceDate
     *
     * @return issuanceDate
     **/

    public Long getIssuanceDate() {
        return issuanceDate;
    }

    public void setIssuanceDate(Long issuanceDate) {
        this.issuanceDate = issuanceDate;
    }

    public InvoiceSrv deliveryDate(Long deliveryDate) {
        this.deliveryDate = deliveryDate;
        return this;
    }

    /**
     * Get deliveryDate
     *
     * @return deliveryDate
     **/

    public Long getDeliveryDate() {
        return deliveryDate;
    }

    public void setDeliveryDate(Long deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    public InvoiceSrv billNumber(String billNumber) {
        this.billNumber = billNumber;
        return this;
    }

    /**
     * Get billNumber
     *
     * @return billNumber
     **/

    public String getBillNumber() {
        return billNumber;
    }

    public void setBillNumber(String billNumber) {
        this.billNumber = billNumber;
    }

    public InvoiceSrv issuancePersianDate(String issuancePersianDate) {
        this.issuancePersianDate = issuancePersianDate;
        return this;
    }

    /**
     * Get issuancePersianDate
     *
     * @return issuancePersianDate
     **/

    public String getIssuancePersianDate() {
        return issuancePersianDate;
    }

    public void setIssuancePersianDate(String issuancePersianDate) {
        this.issuancePersianDate = issuancePersianDate;
    }

    public InvoiceSrv paymentBillNumber(String paymentBillNumber) {
        this.paymentBillNumber = paymentBillNumber;
        return this;
    }

    /**
     * Get paymentBillNumber
     *
     * @return paymentBillNumber
     **/

    public String getPaymentBillNumber() {
        return paymentBillNumber;
    }

    public void setPaymentBillNumber(String paymentBillNumber) {
        this.paymentBillNumber = paymentBillNumber;
    }

    public InvoiceSrv transactionReferenceId(String transactionReferenceId) {
        this.transactionReferenceId = transactionReferenceId;
        return this;
    }

    /**
     * Get transactionReferenceId
     *
     * @return transactionReferenceId
     **/

    public String getTransactionReferenceId() {
        return transactionReferenceId;
    }

    public void setTransactionReferenceId(String transactionReferenceId) {
        this.transactionReferenceId = transactionReferenceId;
    }

    public InvoiceSrv uniqueNumber(String uniqueNumber) {
        this.uniqueNumber = uniqueNumber;
        return this;
    }

    /**
     * Get uniqueNumber
     *
     * @return uniqueNumber
     **/

    public String getUniqueNumber() {
        return uniqueNumber;
    }

    public void setUniqueNumber(String uniqueNumber) {
        this.uniqueNumber = uniqueNumber;
    }

    public InvoiceSrv description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get description
     *
     * @return description
     **/

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public InvoiceSrv paymentDate(Long paymentDate) {
        this.paymentDate = paymentDate;
        return this;
    }

    /**
     * Get paymentDate
     *
     * @return paymentDate
     **/

    public Long getPaymentDate() {
        return paymentDate;
    }

    public void setPaymentDate(Long paymentDate) {
        this.paymentDate = paymentDate;
    }

    public InvoiceSrv payed(Boolean payed) {
        this.payed = payed;
        return this;
    }

    /**
     * Get payed
     *
     * @return payed
     **/

    public Boolean isPayed() {
        return payed;
    }

    public void setPayed(Boolean payed) {
        this.payed = payed;
    }

    public InvoiceSrv canceled(Boolean canceled) {
        this.canceled = canceled;
        return this;
    }

    /**
     * Get canceled
     *
     * @return canceled
     **/

    public Boolean isCanceled() {
        return canceled;
    }

    public void setCanceled(Boolean canceled) {
        this.canceled = canceled;
    }

    public InvoiceSrv cancelDate(Long cancelDate) {
        this.cancelDate = cancelDate;
        return this;
    }

    /**
     * Get cancelDate
     *
     * @return cancelDate
     **/

    public Long getCancelDate() {
        return cancelDate;
    }

    public void setCancelDate(Long cancelDate) {
        this.cancelDate = cancelDate;
    }

    public InvoiceSrv business(BusinessSoftSrv business) {
        this.business = business;
        return this;
    }

    /**
     * Get business
     *
     * @return business
     **/

    public BusinessSoftSrv getBusiness() {
        return business;
    }

    public void setBusiness(BusinessSoftSrv business) {
        this.business = business;
    }

    public InvoiceSrv invoiceItemSrvs(List<InvoiceItemSrv> invoiceItemSrvs) {
        this.invoiceItemSrvs = invoiceItemSrvs;
        return this;
    }

    public InvoiceSrv addInvoiceItemSrvsItem(InvoiceItemSrv invoiceItemSrvsItem) {
        if (this.invoiceItemSrvs == null) {
            this.invoiceItemSrvs = new ArrayList<InvoiceItemSrv>();
        }
        this.invoiceItemSrvs.add(invoiceItemSrvsItem);
        return this;
    }

    /**
     * Get invoiceItemSrvs
     *
     * @return invoiceItemSrvs
     **/

    public List<InvoiceItemSrv> getInvoiceItemSrvs() {
        return invoiceItemSrvs;
    }

    public void setInvoiceItemSrvs(List<InvoiceItemSrv> invoiceItemSrvs) {
        this.invoiceItemSrvs = invoiceItemSrvs;
    }

    public InvoiceSrv guildSrv(GuildSrv guildSrv) {
        this.guildSrv = guildSrv;
        return this;
    }

    /**
     * Get guildSrv
     *
     * @return guildSrv
     **/

    public GuildSrv getGuildSrv() {
        return guildSrv;
    }

    public void setGuildSrv(GuildSrv guildSrv) {
        this.guildSrv = guildSrv;
    }

    public InvoiceSrv addressSrv(AddressSrv addressSrv) {
        this.addressSrv = addressSrv;
        return this;
    }

    /**
     * Get addressSrv
     *
     * @return addressSrv
     **/

    public AddressSrv getAddressSrv() {
        return addressSrv;
    }

    public void setAddressSrv(AddressSrv addressSrv) {
        this.addressSrv = addressSrv;
    }

    public InvoiceSrv userSrv(UserSrv userSrv) {
        this.userSrv = userSrv;
        return this;
    }

    /**
     * Get userSrv
     *
     * @return userSrv
     **/

    public UserSrv getUserSrv() {
        return userSrv;
    }

    public void setUserSrv(UserSrv userSrv) {
        this.userSrv = userSrv;
    }

    public InvoiceSrv phoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
        return this;
    }

    /**
     * Get phoneNumber
     *
     * @return phoneNumber
     **/

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public InvoiceSrv cellphoneNumber(String cellphoneNumber) {
        this.cellphoneNumber = cellphoneNumber;
        return this;
    }

    /**
     * Get cellphoneNumber
     *
     * @return cellphoneNumber
     **/

    public String getCellphoneNumber() {
        return cellphoneNumber;
    }

    public void setCellphoneNumber(String cellphoneNumber) {
        this.cellphoneNumber = cellphoneNumber;
    }

    public InvoiceSrv closed(Boolean closed) {
        this.closed = closed;
        return this;
    }

    /**
     * Get closed
     *
     * @return closed
     **/

    public Boolean isClosed() {
        return closed;
    }

    public void setClosed(Boolean closed) {
        this.closed = closed;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InvoiceSrv invoiceSrv = (InvoiceSrv) o;
        return Objects.equals(this.id, invoiceSrv.id) &&
                Objects.equals(this.totalAmount, invoiceSrv.totalAmount) &&
                Objects.equals(this.payableAmount, invoiceSrv.payableAmount) &&
                Objects.equals(this.vat, invoiceSrv.vat) &&
                Objects.equals(this.issuanceDate, invoiceSrv.issuanceDate) &&
                Objects.equals(this.deliveryDate, invoiceSrv.deliveryDate) &&
                Objects.equals(this.billNumber, invoiceSrv.billNumber) &&
                Objects.equals(this.issuancePersianDate, invoiceSrv.issuancePersianDate) &&
                Objects.equals(this.paymentBillNumber, invoiceSrv.paymentBillNumber) &&
                Objects.equals(this.transactionReferenceId, invoiceSrv.transactionReferenceId) &&
                Objects.equals(this.uniqueNumber, invoiceSrv.uniqueNumber) &&
                Objects.equals(this.description, invoiceSrv.description) &&
                Objects.equals(this.paymentDate, invoiceSrv.paymentDate) &&
                Objects.equals(this.payed, invoiceSrv.payed) &&
                Objects.equals(this.canceled, invoiceSrv.canceled) &&
                Objects.equals(this.cancelDate, invoiceSrv.cancelDate) &&
                Objects.equals(this.business, invoiceSrv.business) &&
                Objects.equals(this.invoiceItemSrvs, invoiceSrv.invoiceItemSrvs) &&
                Objects.equals(this.guildSrv, invoiceSrv.guildSrv) &&
                Objects.equals(this.addressSrv, invoiceSrv.addressSrv) &&
                Objects.equals(this.userSrv, invoiceSrv.userSrv) &&
                Objects.equals(this.phoneNumber, invoiceSrv.phoneNumber) &&
                Objects.equals(this.cellphoneNumber, invoiceSrv.cellphoneNumber) &&
                Objects.equals(this.closed, invoiceSrv.closed);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, totalAmount, payableAmount, vat, issuanceDate, deliveryDate, billNumber, issuancePersianDate, paymentBillNumber, transactionReferenceId, uniqueNumber, description, paymentDate, payed, canceled, cancelDate, business, invoiceItemSrvs, guildSrv, addressSrv, userSrv, phoneNumber, cellphoneNumber, closed);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InvoiceSrv {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    totalAmount: ").append(toIndentedString(totalAmount)).append("\n");
        sb.append("    payableAmount: ").append(toIndentedString(payableAmount)).append("\n");
        sb.append("    vat: ").append(toIndentedString(vat)).append("\n");
        sb.append("    issuanceDate: ").append(toIndentedString(issuanceDate)).append("\n");
        sb.append("    deliveryDate: ").append(toIndentedString(deliveryDate)).append("\n");
        sb.append("    billNumber: ").append(toIndentedString(billNumber)).append("\n");
        sb.append("    issuancePersianDate: ").append(toIndentedString(issuancePersianDate)).append("\n");
        sb.append("    paymentBillNumber: ").append(toIndentedString(paymentBillNumber)).append("\n");
        sb.append("    transactionReferenceId: ").append(toIndentedString(transactionReferenceId)).append("\n");
        sb.append("    uniqueNumber: ").append(toIndentedString(uniqueNumber)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    paymentDate: ").append(toIndentedString(paymentDate)).append("\n");
        sb.append("    payed: ").append(toIndentedString(payed)).append("\n");
        sb.append("    canceled: ").append(toIndentedString(canceled)).append("\n");
        sb.append("    cancelDate: ").append(toIndentedString(cancelDate)).append("\n");
        sb.append("    business: ").append(toIndentedString(business)).append("\n");
        sb.append("    invoiceItemSrvs: ").append(toIndentedString(invoiceItemSrvs)).append("\n");
        sb.append("    guildSrv: ").append(toIndentedString(guildSrv)).append("\n");
        sb.append("    addressSrv: ").append(toIndentedString(addressSrv)).append("\n");
        sb.append("    userSrv: ").append(toIndentedString(userSrv)).append("\n");
        sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
        sb.append("    cellphoneNumber: ").append(toIndentedString(cellphoneNumber)).append("\n");
        sb.append("    closed: ").append(toIndentedString(closed)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

