/*
 * Fanapium Core API
 * Fanapium B2B2C services
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.springframework.social.fanapium.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;

/**
 * InvoiceItemSrv
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-02T09:35:11.370+04:30")
public class InvoiceItemSrv {
    @JsonProperty("id")
    private Long id = null;

    @JsonProperty("productSrv")
    private ProductSrv productSrv = null;

    @JsonProperty("amount")
    private Long amount = null;

    @JsonProperty("description")
    private String description = null;

    @JsonProperty("quantity")
    private Integer quantity = null;

    public InvoiceItemSrv id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public InvoiceItemSrv productSrv(ProductSrv productSrv) {
        this.productSrv = productSrv;
        return this;
    }

    /**
     * Get productSrv
     *
     * @return productSrv
     **/

    public ProductSrv getProductSrv() {
        return productSrv;
    }

    public void setProductSrv(ProductSrv productSrv) {
        this.productSrv = productSrv;
    }

    public InvoiceItemSrv amount(Long amount) {
        this.amount = amount;
        return this;
    }

    /**
     * Get amount
     *
     * @return amount
     **/

    public Long getAmount() {
        return amount;
    }

    public void setAmount(Long amount) {
        this.amount = amount;
    }

    public InvoiceItemSrv description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get description
     *
     * @return description
     **/

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public InvoiceItemSrv quantity(Integer quantity) {
        this.quantity = quantity;
        return this;
    }

    /**
     * Get quantity
     *
     * @return quantity
     **/

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InvoiceItemSrv invoiceItemSrv = (InvoiceItemSrv) o;
        return Objects.equals(this.id, invoiceItemSrv.id) &&
                Objects.equals(this.productSrv, invoiceItemSrv.productSrv) &&
                Objects.equals(this.amount, invoiceItemSrv.amount) &&
                Objects.equals(this.description, invoiceItemSrv.description) &&
                Objects.equals(this.quantity, invoiceItemSrv.quantity);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, productSrv, amount, description, quantity);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InvoiceItemSrv {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    productSrv: ").append(toIndentedString(productSrv)).append("\n");
        sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

