/*
 * Fanapium Core API
 * Fanapium B2B2C services
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.springframework.social.fanapium.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ProductSrv
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-02T09:35:11.370+04:30")
public class ProductSrv {
    @JsonProperty("id")
    private Long id = null;

    @JsonProperty("timelineId")
    private Long timelineId = null;

    @JsonProperty("entityId")
    private Long entityId = null;

    @JsonProperty("numOfLikes")
    private Integer numOfLikes = null;

    @JsonProperty("numOfFavorites")
    private Integer numOfFavorites = null;

    @JsonProperty("numOfComments")
    private Integer numOfComments = null;

    @JsonProperty("timestamp")
    private Long timestamp = null;

    @JsonProperty("enable")
    private Boolean enable = null;

    @JsonProperty("hide")
    private Boolean hide = null;

    @JsonProperty("business")
    private BusinessSoftSrv business = null;

    @JsonProperty("userPostInfo")
    private UserPostInfoSrv userPostInfo = null;

    @JsonProperty("metadata")
    private String metadata = null;

    @JsonProperty("latitude")
    private Double latitude = null;

    @JsonProperty("longitude")
    private Double longitude = null;

    @JsonProperty("canComment")
    private Boolean canComment = null;

    @JsonProperty("canLike")
    private Boolean canLike = null;

    @JsonProperty("tags")
    private List<String> tags = null;

    @JsonProperty("name")
    private String name = null;

    @JsonProperty("description")
    private String description = null;

    @JsonProperty("categoryList")
    private List<String> categoryList = null;

    @JsonProperty("previewInfo")
    private ImageInfoSrv previewInfo = null;

    @JsonProperty("preview")
    private String preview = null;

    @JsonProperty("availableCount")
    private Integer availableCount = null;

    @JsonProperty("price")
    private Long price = null;

    @JsonProperty("discount")
    private Long discount = null;

    @JsonProperty("rate")
    private RateSrv rate = null;

    @JsonProperty("saleInfo")
    private SaleInfo saleInfo = null;

    @JsonProperty("attributeValues")
    private List<AttributeValueSrv> attributeValues = null;

    @JsonProperty("guilds")
    private List<GuildSrv> guilds = null;

    @JsonProperty("templateCode")
    private String templateCode = null;

    @JsonProperty("subProducts")
    private List<SubProductSrv> subProducts = null;

    @JsonProperty("productGroup")
    private ProductGroupSrv productGroup = null;

    @JsonProperty("content")
    private String content = null;

    @JsonProperty("currency")
    private CurrencySrv currency = null;

    public ProductSrv id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public ProductSrv timelineId(Long timelineId) {
        this.timelineId = timelineId;
        return this;
    }

    /**
     * Get timelineId
     *
     * @return timelineId
     **/

    public Long getTimelineId() {
        return timelineId;
    }

    public void setTimelineId(Long timelineId) {
        this.timelineId = timelineId;
    }

    public ProductSrv entityId(Long entityId) {
        this.entityId = entityId;
        return this;
    }

    /**
     * Get entityId
     *
     * @return entityId
     **/

    public Long getEntityId() {
        return entityId;
    }

    public void setEntityId(Long entityId) {
        this.entityId = entityId;
    }

    public ProductSrv numOfLikes(Integer numOfLikes) {
        this.numOfLikes = numOfLikes;
        return this;
    }

    /**
     * Get numOfLikes
     *
     * @return numOfLikes
     **/

    public Integer getNumOfLikes() {
        return numOfLikes;
    }

    public void setNumOfLikes(Integer numOfLikes) {
        this.numOfLikes = numOfLikes;
    }

    public ProductSrv numOfFavorites(Integer numOfFavorites) {
        this.numOfFavorites = numOfFavorites;
        return this;
    }

    /**
     * Get numOfFavorites
     *
     * @return numOfFavorites
     **/

    public Integer getNumOfFavorites() {
        return numOfFavorites;
    }

    public void setNumOfFavorites(Integer numOfFavorites) {
        this.numOfFavorites = numOfFavorites;
    }

    public ProductSrv numOfComments(Integer numOfComments) {
        this.numOfComments = numOfComments;
        return this;
    }

    /**
     * Get numOfComments
     *
     * @return numOfComments
     **/

    public Integer getNumOfComments() {
        return numOfComments;
    }

    public void setNumOfComments(Integer numOfComments) {
        this.numOfComments = numOfComments;
    }

    public ProductSrv timestamp(Long timestamp) {
        this.timestamp = timestamp;
        return this;
    }

    /**
     * Get timestamp
     *
     * @return timestamp
     **/

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    public ProductSrv enable(Boolean enable) {
        this.enable = enable;
        return this;
    }

    /**
     * Get enable
     *
     * @return enable
     **/

    public Boolean isEnable() {
        return enable;
    }

    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    public ProductSrv hide(Boolean hide) {
        this.hide = hide;
        return this;
    }

    /**
     * Get hide
     *
     * @return hide
     **/

    public Boolean isHide() {
        return hide;
    }

    public void setHide(Boolean hide) {
        this.hide = hide;
    }

    public ProductSrv business(BusinessSoftSrv business) {
        this.business = business;
        return this;
    }

    /**
     * Get business
     *
     * @return business
     **/

    public BusinessSoftSrv getBusiness() {
        return business;
    }

    public void setBusiness(BusinessSoftSrv business) {
        this.business = business;
    }

    public ProductSrv userPostInfo(UserPostInfoSrv userPostInfo) {
        this.userPostInfo = userPostInfo;
        return this;
    }

    /**
     * Get userPostInfo
     *
     * @return userPostInfo
     **/

    public UserPostInfoSrv getUserPostInfo() {
        return userPostInfo;
    }

    public void setUserPostInfo(UserPostInfoSrv userPostInfo) {
        this.userPostInfo = userPostInfo;
    }

    public ProductSrv metadata(String metadata) {
        this.metadata = metadata;
        return this;
    }

    /**
     * Get metadata
     *
     * @return metadata
     **/

    public String getMetadata() {
        return metadata;
    }

    public void setMetadata(String metadata) {
        this.metadata = metadata;
    }

    public ProductSrv latitude(Double latitude) {
        this.latitude = latitude;
        return this;
    }

    /**
     * Get latitude
     *
     * @return latitude
     **/

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public ProductSrv longitude(Double longitude) {
        this.longitude = longitude;
        return this;
    }

    /**
     * Get longitude
     *
     * @return longitude
     **/

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public ProductSrv canComment(Boolean canComment) {
        this.canComment = canComment;
        return this;
    }

    /**
     * Get canComment
     *
     * @return canComment
     **/

    public Boolean isCanComment() {
        return canComment;
    }

    public void setCanComment(Boolean canComment) {
        this.canComment = canComment;
    }

    public ProductSrv canLike(Boolean canLike) {
        this.canLike = canLike;
        return this;
    }

    /**
     * Get canLike
     *
     * @return canLike
     **/

    public Boolean isCanLike() {
        return canLike;
    }

    public void setCanLike(Boolean canLike) {
        this.canLike = canLike;
    }

    public ProductSrv tags(List<String> tags) {
        this.tags = tags;
        return this;
    }

    public ProductSrv addTagsItem(String tagsItem) {
        if (this.tags == null) {
            this.tags = new ArrayList<String>();
        }
        this.tags.add(tagsItem);
        return this;
    }

    /**
     * Get tags
     *
     * @return tags
     **/

    public List<String> getTags() {
        return tags;
    }

    public void setTags(List<String> tags) {
        this.tags = tags;
    }

    public ProductSrv name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public ProductSrv description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get description
     *
     * @return description
     **/

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public ProductSrv categoryList(List<String> categoryList) {
        this.categoryList = categoryList;
        return this;
    }

    public ProductSrv addCategoryListItem(String categoryListItem) {
        if (this.categoryList == null) {
            this.categoryList = new ArrayList<String>();
        }
        this.categoryList.add(categoryListItem);
        return this;
    }

    /**
     * Get categoryList
     *
     * @return categoryList
     **/

    public List<String> getCategoryList() {
        return categoryList;
    }

    public void setCategoryList(List<String> categoryList) {
        this.categoryList = categoryList;
    }

    public ProductSrv previewInfo(ImageInfoSrv previewInfo) {
        this.previewInfo = previewInfo;
        return this;
    }

    /**
     * Get previewInfo
     *
     * @return previewInfo
     **/

    public ImageInfoSrv getPreviewInfo() {
        return previewInfo;
    }

    public void setPreviewInfo(ImageInfoSrv previewInfo) {
        this.previewInfo = previewInfo;
    }

    public ProductSrv preview(String preview) {
        this.preview = preview;
        return this;
    }

    /**
     * Get preview
     *
     * @return preview
     **/

    public String getPreview() {
        return preview;
    }

    public void setPreview(String preview) {
        this.preview = preview;
    }

    public ProductSrv availableCount(Integer availableCount) {
        this.availableCount = availableCount;
        return this;
    }

    /**
     * Get availableCount
     *
     * @return availableCount
     **/

    public Integer getAvailableCount() {
        return availableCount;
    }

    public void setAvailableCount(Integer availableCount) {
        this.availableCount = availableCount;
    }

    public ProductSrv price(Long price) {
        this.price = price;
        return this;
    }

    /**
     * Get price
     *
     * @return price
     **/

    public Long getPrice() {
        return price;
    }

    public void setPrice(Long price) {
        this.price = price;
    }

    public ProductSrv discount(Long discount) {
        this.discount = discount;
        return this;
    }

    /**
     * Get discount
     *
     * @return discount
     **/

    public Long getDiscount() {
        return discount;
    }

    public void setDiscount(Long discount) {
        this.discount = discount;
    }

    public ProductSrv rate(RateSrv rate) {
        this.rate = rate;
        return this;
    }

    /**
     * Get rate
     *
     * @return rate
     **/

    public RateSrv getRate() {
        return rate;
    }

    public void setRate(RateSrv rate) {
        this.rate = rate;
    }

    public ProductSrv saleInfo(SaleInfo saleInfo) {
        this.saleInfo = saleInfo;
        return this;
    }

    /**
     * Get saleInfo
     *
     * @return saleInfo
     **/

    public SaleInfo getSaleInfo() {
        return saleInfo;
    }

    public void setSaleInfo(SaleInfo saleInfo) {
        this.saleInfo = saleInfo;
    }

    public ProductSrv attributeValues(List<AttributeValueSrv> attributeValues) {
        this.attributeValues = attributeValues;
        return this;
    }

    public ProductSrv addAttributeValuesItem(AttributeValueSrv attributeValuesItem) {
        if (this.attributeValues == null) {
            this.attributeValues = new ArrayList<AttributeValueSrv>();
        }
        this.attributeValues.add(attributeValuesItem);
        return this;
    }

    /**
     * Get attributeValues
     *
     * @return attributeValues
     **/

    public List<AttributeValueSrv> getAttributeValues() {
        return attributeValues;
    }

    public void setAttributeValues(List<AttributeValueSrv> attributeValues) {
        this.attributeValues = attributeValues;
    }

    public ProductSrv guilds(List<GuildSrv> guilds) {
        this.guilds = guilds;
        return this;
    }

    public ProductSrv addGuildsItem(GuildSrv guildsItem) {
        if (this.guilds == null) {
            this.guilds = new ArrayList<GuildSrv>();
        }
        this.guilds.add(guildsItem);
        return this;
    }

    /**
     * Get guilds
     *
     * @return guilds
     **/

    public List<GuildSrv> getGuilds() {
        return guilds;
    }

    public void setGuilds(List<GuildSrv> guilds) {
        this.guilds = guilds;
    }

    public ProductSrv templateCode(String templateCode) {
        this.templateCode = templateCode;
        return this;
    }

    /**
     * Get templateCode
     *
     * @return templateCode
     **/

    public String getTemplateCode() {
        return templateCode;
    }

    public void setTemplateCode(String templateCode) {
        this.templateCode = templateCode;
    }

    public ProductSrv subProducts(List<SubProductSrv> subProducts) {
        this.subProducts = subProducts;
        return this;
    }

    public ProductSrv addSubProductsItem(SubProductSrv subProductsItem) {
        if (this.subProducts == null) {
            this.subProducts = new ArrayList<SubProductSrv>();
        }
        this.subProducts.add(subProductsItem);
        return this;
    }

    /**
     * Get subProducts
     *
     * @return subProducts
     **/

    public List<SubProductSrv> getSubProducts() {
        return subProducts;
    }

    public void setSubProducts(List<SubProductSrv> subProducts) {
        this.subProducts = subProducts;
    }

    public ProductSrv productGroup(ProductGroupSrv productGroup) {
        this.productGroup = productGroup;
        return this;
    }

    /**
     * Get productGroup
     *
     * @return productGroup
     **/

    public ProductGroupSrv getProductGroup() {
        return productGroup;
    }

    public void setProductGroup(ProductGroupSrv productGroup) {
        this.productGroup = productGroup;
    }

    public ProductSrv content(String content) {
        this.content = content;
        return this;
    }

    /**
     * Get content
     *
     * @return content
     **/

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public ProductSrv currency(CurrencySrv currency) {
        this.currency = currency;
        return this;
    }

    /**
     * Get currency
     *
     * @return currency
     **/

    public CurrencySrv getCurrency() {
        return currency;
    }

    public void setCurrency(CurrencySrv currency) {
        this.currency = currency;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ProductSrv productSrv = (ProductSrv) o;
        return Objects.equals(this.id, productSrv.id) &&
                Objects.equals(this.timelineId, productSrv.timelineId) &&
                Objects.equals(this.entityId, productSrv.entityId) &&
                Objects.equals(this.numOfLikes, productSrv.numOfLikes) &&
                Objects.equals(this.numOfFavorites, productSrv.numOfFavorites) &&
                Objects.equals(this.numOfComments, productSrv.numOfComments) &&
                Objects.equals(this.timestamp, productSrv.timestamp) &&
                Objects.equals(this.enable, productSrv.enable) &&
                Objects.equals(this.hide, productSrv.hide) &&
                Objects.equals(this.business, productSrv.business) &&
                Objects.equals(this.userPostInfo, productSrv.userPostInfo) &&
                Objects.equals(this.metadata, productSrv.metadata) &&
                Objects.equals(this.latitude, productSrv.latitude) &&
                Objects.equals(this.longitude, productSrv.longitude) &&
                Objects.equals(this.canComment, productSrv.canComment) &&
                Objects.equals(this.canLike, productSrv.canLike) &&
                Objects.equals(this.tags, productSrv.tags) &&
                Objects.equals(this.name, productSrv.name) &&
                Objects.equals(this.description, productSrv.description) &&
                Objects.equals(this.categoryList, productSrv.categoryList) &&
                Objects.equals(this.previewInfo, productSrv.previewInfo) &&
                Objects.equals(this.preview, productSrv.preview) &&
                Objects.equals(this.availableCount, productSrv.availableCount) &&
                Objects.equals(this.price, productSrv.price) &&
                Objects.equals(this.discount, productSrv.discount) &&
                Objects.equals(this.rate, productSrv.rate) &&
                Objects.equals(this.saleInfo, productSrv.saleInfo) &&
                Objects.equals(this.attributeValues, productSrv.attributeValues) &&
                Objects.equals(this.guilds, productSrv.guilds) &&
                Objects.equals(this.templateCode, productSrv.templateCode) &&
                Objects.equals(this.subProducts, productSrv.subProducts) &&
                Objects.equals(this.productGroup, productSrv.productGroup) &&
                Objects.equals(this.content, productSrv.content) &&
                Objects.equals(this.currency, productSrv.currency);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, timelineId, entityId, numOfLikes, numOfFavorites, numOfComments, timestamp, enable, hide, business, userPostInfo, metadata, latitude, longitude, canComment, canLike, tags, name, description, categoryList, previewInfo, preview, availableCount, price, discount, rate, saleInfo, attributeValues, guilds, templateCode, subProducts, productGroup, content, currency);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ProductSrv {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    timelineId: ").append(toIndentedString(timelineId)).append("\n");
        sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
        sb.append("    numOfLikes: ").append(toIndentedString(numOfLikes)).append("\n");
        sb.append("    numOfFavorites: ").append(toIndentedString(numOfFavorites)).append("\n");
        sb.append("    numOfComments: ").append(toIndentedString(numOfComments)).append("\n");
        sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
        sb.append("    enable: ").append(toIndentedString(enable)).append("\n");
        sb.append("    hide: ").append(toIndentedString(hide)).append("\n");
        sb.append("    business: ").append(toIndentedString(business)).append("\n");
        sb.append("    userPostInfo: ").append(toIndentedString(userPostInfo)).append("\n");
        sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
        sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
        sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
        sb.append("    canComment: ").append(toIndentedString(canComment)).append("\n");
        sb.append("    canLike: ").append(toIndentedString(canLike)).append("\n");
        sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    categoryList: ").append(toIndentedString(categoryList)).append("\n");
        sb.append("    previewInfo: ").append(toIndentedString(previewInfo)).append("\n");
        sb.append("    preview: ").append(toIndentedString(preview)).append("\n");
        sb.append("    availableCount: ").append(toIndentedString(availableCount)).append("\n");
        sb.append("    price: ").append(toIndentedString(price)).append("\n");
        sb.append("    discount: ").append(toIndentedString(discount)).append("\n");
        sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
        sb.append("    saleInfo: ").append(toIndentedString(saleInfo)).append("\n");
        sb.append("    attributeValues: ").append(toIndentedString(attributeValues)).append("\n");
        sb.append("    guilds: ").append(toIndentedString(guilds)).append("\n");
        sb.append("    templateCode: ").append(toIndentedString(templateCode)).append("\n");
        sb.append("    subProducts: ").append(toIndentedString(subProducts)).append("\n");
        sb.append("    productGroup: ").append(toIndentedString(productGroup)).append("\n");
        sb.append("    content: ").append(toIndentedString(content)).append("\n");
        sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

