/*
 * Fanapium Core API
 * Fanapium B2B2C services
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.springframework.social.fanapium.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;

/**
 * ProductAllocationSrv
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-02T09:35:11.370+04:30")
public class ProductAllocationSrv {
    @JsonProperty("id")
    private Long id = null;

    @JsonProperty("owner")
    private ProductSrv owner = null;

    @JsonProperty("allocated")
    private ProductSrv allocated = null;

    @JsonProperty("description")
    private String description = null;

    @JsonProperty("startDate")
    private Long startDate = null;

    @JsonProperty("endDate")
    private Long endDate = null;

    @JsonProperty("confirmed")
    private Boolean confirmed = null;

    @JsonProperty("finished")
    private Boolean finished = null;

    @JsonProperty("requester")
    private UserSrv requester = null;

    @JsonProperty("confirmer")
    private UserSrv confirmer = null;

    @JsonProperty("deallocator")
    private UserSrv deallocator = null;

    @JsonProperty("allocator")
    private Boolean allocator = null;

    public ProductAllocationSrv id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public ProductAllocationSrv owner(ProductSrv owner) {
        this.owner = owner;
        return this;
    }

    /**
     * Get owner
     *
     * @return owner
     **/

    public ProductSrv getOwner() {
        return owner;
    }

    public void setOwner(ProductSrv owner) {
        this.owner = owner;
    }

    public ProductAllocationSrv allocated(ProductSrv allocated) {
        this.allocated = allocated;
        return this;
    }

    /**
     * Get allocated
     *
     * @return allocated
     **/

    public ProductSrv getAllocated() {
        return allocated;
    }

    public void setAllocated(ProductSrv allocated) {
        this.allocated = allocated;
    }

    public ProductAllocationSrv description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get description
     *
     * @return description
     **/

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public ProductAllocationSrv startDate(Long startDate) {
        this.startDate = startDate;
        return this;
    }

    /**
     * Get startDate
     *
     * @return startDate
     **/

    public Long getStartDate() {
        return startDate;
    }

    public void setStartDate(Long startDate) {
        this.startDate = startDate;
    }

    public ProductAllocationSrv endDate(Long endDate) {
        this.endDate = endDate;
        return this;
    }

    /**
     * Get endDate
     *
     * @return endDate
     **/

    public Long getEndDate() {
        return endDate;
    }

    public void setEndDate(Long endDate) {
        this.endDate = endDate;
    }

    public ProductAllocationSrv confirmed(Boolean confirmed) {
        this.confirmed = confirmed;
        return this;
    }

    /**
     * Get confirmed
     *
     * @return confirmed
     **/

    public Boolean isConfirmed() {
        return confirmed;
    }

    public void setConfirmed(Boolean confirmed) {
        this.confirmed = confirmed;
    }

    public ProductAllocationSrv finished(Boolean finished) {
        this.finished = finished;
        return this;
    }

    /**
     * Get finished
     *
     * @return finished
     **/

    public Boolean isFinished() {
        return finished;
    }

    public void setFinished(Boolean finished) {
        this.finished = finished;
    }

    public ProductAllocationSrv requester(UserSrv requester) {
        this.requester = requester;
        return this;
    }

    /**
     * Get requester
     *
     * @return requester
     **/

    public UserSrv getRequester() {
        return requester;
    }

    public void setRequester(UserSrv requester) {
        this.requester = requester;
    }

    public ProductAllocationSrv confirmer(UserSrv confirmer) {
        this.confirmer = confirmer;
        return this;
    }

    /**
     * Get confirmer
     *
     * @return confirmer
     **/

    public UserSrv getConfirmer() {
        return confirmer;
    }

    public void setConfirmer(UserSrv confirmer) {
        this.confirmer = confirmer;
    }

    public ProductAllocationSrv deallocator(UserSrv deallocator) {
        this.deallocator = deallocator;
        return this;
    }

    /**
     * Get deallocator
     *
     * @return deallocator
     **/

    public UserSrv getDeallocator() {
        return deallocator;
    }

    public void setDeallocator(UserSrv deallocator) {
        this.deallocator = deallocator;
    }

    public ProductAllocationSrv allocator(Boolean allocator) {
        this.allocator = allocator;
        return this;
    }

    /**
     * Get allocator
     *
     * @return allocator
     **/

    public Boolean isAllocator() {
        return allocator;
    }

    public void setAllocator(Boolean allocator) {
        this.allocator = allocator;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ProductAllocationSrv productAllocationSrv = (ProductAllocationSrv) o;
        return Objects.equals(this.id, productAllocationSrv.id) &&
                Objects.equals(this.owner, productAllocationSrv.owner) &&
                Objects.equals(this.allocated, productAllocationSrv.allocated) &&
                Objects.equals(this.description, productAllocationSrv.description) &&
                Objects.equals(this.startDate, productAllocationSrv.startDate) &&
                Objects.equals(this.endDate, productAllocationSrv.endDate) &&
                Objects.equals(this.confirmed, productAllocationSrv.confirmed) &&
                Objects.equals(this.finished, productAllocationSrv.finished) &&
                Objects.equals(this.requester, productAllocationSrv.requester) &&
                Objects.equals(this.confirmer, productAllocationSrv.confirmer) &&
                Objects.equals(this.deallocator, productAllocationSrv.deallocator) &&
                Objects.equals(this.allocator, productAllocationSrv.allocator);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, owner, allocated, description, startDate, endDate, confirmed, finished, requester, confirmer, deallocator, allocator);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ProductAllocationSrv {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
        sb.append("    allocated: ").append(toIndentedString(allocated)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
        sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
        sb.append("    confirmed: ").append(toIndentedString(confirmed)).append("\n");
        sb.append("    finished: ").append(toIndentedString(finished)).append("\n");
        sb.append("    requester: ").append(toIndentedString(requester)).append("\n");
        sb.append("    confirmer: ").append(toIndentedString(confirmer)).append("\n");
        sb.append("    deallocator: ").append(toIndentedString(deallocator)).append("\n");
        sb.append("    allocator: ").append(toIndentedString(allocator)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

