/*
 * Fanapium Core API
 * Fanapium B2B2C services
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.springframework.social.fanapium.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;

/**
 * RateSrv
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-02T09:35:11.370+04:30")
public class RateSrv {
    @JsonProperty("rate")
    private Double rate = null;

    @JsonProperty("rateCount")
    private Long rateCount = null;

    public RateSrv rate(Double rate) {
        this.rate = rate;
        return this;
    }

    /**
     * Get rate
     *
     * @return rate
     **/

    public Double getRate() {
        return rate;
    }

    public void setRate(Double rate) {
        this.rate = rate;
    }

    public RateSrv rateCount(Long rateCount) {
        this.rateCount = rateCount;
        return this;
    }

    /**
     * Get rateCount
     *
     * @return rateCount
     **/

    public Long getRateCount() {
        return rateCount;
    }

    public void setRateCount(Long rateCount) {
        this.rateCount = rateCount;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RateSrv rateSrv = (RateSrv) o;
        return Objects.equals(this.rate, rateSrv.rate) &&
                Objects.equals(this.rateCount, rateSrv.rateCount);
    }

    @Override
    public int hashCode() {
        return Objects.hash(rate, rateCount);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class RateSrv {\n");

        sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
        sb.append("    rateCount: ").append(toIndentedString(rateCount)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

