/*
 * Fanapium Core API
 * Fanapium B2B2C services
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.springframework.social.fanapium.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * SearchProductSrv
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-02T09:35:11.370+04:30")
public class SearchProductSrv {
    @JsonProperty("products")
    private List<ProductSrv> products = null;

    @JsonProperty("guilds")
    private List<GuildSrv> guilds = null;

    public SearchProductSrv products(List<ProductSrv> products) {
        this.products = products;
        return this;
    }

    public SearchProductSrv addProductsItem(ProductSrv productsItem) {
        if (this.products == null) {
            this.products = new ArrayList<ProductSrv>();
        }
        this.products.add(productsItem);
        return this;
    }

    /**
     * Get products
     *
     * @return products
     **/

    public List<ProductSrv> getProducts() {
        return products;
    }

    public void setProducts(List<ProductSrv> products) {
        this.products = products;
    }

    public SearchProductSrv guilds(List<GuildSrv> guilds) {
        this.guilds = guilds;
        return this;
    }

    public SearchProductSrv addGuildsItem(GuildSrv guildsItem) {
        if (this.guilds == null) {
            this.guilds = new ArrayList<GuildSrv>();
        }
        this.guilds.add(guildsItem);
        return this;
    }

    /**
     * Get guilds
     *
     * @return guilds
     **/

    public List<GuildSrv> getGuilds() {
        return guilds;
    }

    public void setGuilds(List<GuildSrv> guilds) {
        this.guilds = guilds;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SearchProductSrv searchProductSrv = (SearchProductSrv) o;
        return Objects.equals(this.products, searchProductSrv.products) &&
                Objects.equals(this.guilds, searchProductSrv.guilds);
    }

    @Override
    public int hashCode() {
        return Objects.hash(products, guilds);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SearchProductSrv {\n");

        sb.append("    products: ").append(toIndentedString(products)).append("\n");
        sb.append("    guilds: ").append(toIndentedString(guilds)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

