/*
 * Fanapium Core API
 * Fanapium B2B2C services
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.springframework.social.fanapium.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * SettlementRequestSrv
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-02T09:35:11.370+04:30")
public class SettlementRequestSrv {
    @JsonProperty("id")
    private Long id = null;

    @JsonProperty("amount")
    private Double amount = null;

    @JsonProperty("requestDate")
    private Long requestDate = null;

    @JsonProperty("customerProfileSrv")
    private CustomerProfileSrv customerProfileSrv = null;

    @JsonProperty("settleDate")
    private Long settleDate = null;

    @JsonProperty("status")
    private String status = null;

    @JsonProperty("customerAmountSrvs")
    private List<CustomerAmountSrv> customerAmountSrvs = null;

    @JsonProperty("currency")
    private CurrencySrv currency = null;

    @JsonProperty("toolCode")
    private String toolCode = null;

    @JsonProperty("toolId")
    private String toolId = null;

    @JsonProperty("settlementLogSrvs")
    private List<SettlementLogSrv> settlementLogSrvs = null;

    public SettlementRequestSrv id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public SettlementRequestSrv amount(Double amount) {
        this.amount = amount;
        return this;
    }

    /**
     * Get amount
     *
     * @return amount
     **/

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public SettlementRequestSrv requestDate(Long requestDate) {
        this.requestDate = requestDate;
        return this;
    }

    /**
     * Get requestDate
     *
     * @return requestDate
     **/

    public Long getRequestDate() {
        return requestDate;
    }

    public void setRequestDate(Long requestDate) {
        this.requestDate = requestDate;
    }

    public SettlementRequestSrv customerProfileSrv(CustomerProfileSrv customerProfileSrv) {
        this.customerProfileSrv = customerProfileSrv;
        return this;
    }

    /**
     * Get customerProfileSrv
     *
     * @return customerProfileSrv
     **/

    public CustomerProfileSrv getCustomerProfileSrv() {
        return customerProfileSrv;
    }

    public void setCustomerProfileSrv(CustomerProfileSrv customerProfileSrv) {
        this.customerProfileSrv = customerProfileSrv;
    }

    public SettlementRequestSrv settleDate(Long settleDate) {
        this.settleDate = settleDate;
        return this;
    }

    /**
     * Get settleDate
     *
     * @return settleDate
     **/

    public Long getSettleDate() {
        return settleDate;
    }

    public void setSettleDate(Long settleDate) {
        this.settleDate = settleDate;
    }

    public SettlementRequestSrv status(String status) {
        this.status = status;
        return this;
    }

    /**
     * Get status
     *
     * @return status
     **/

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public SettlementRequestSrv customerAmountSrvs(List<CustomerAmountSrv> customerAmountSrvs) {
        this.customerAmountSrvs = customerAmountSrvs;
        return this;
    }

    public SettlementRequestSrv addCustomerAmountSrvsItem(CustomerAmountSrv customerAmountSrvsItem) {
        if (this.customerAmountSrvs == null) {
            this.customerAmountSrvs = new ArrayList<CustomerAmountSrv>();
        }
        this.customerAmountSrvs.add(customerAmountSrvsItem);
        return this;
    }

    /**
     * Get customerAmountSrvs
     *
     * @return customerAmountSrvs
     **/

    public List<CustomerAmountSrv> getCustomerAmountSrvs() {
        return customerAmountSrvs;
    }

    public void setCustomerAmountSrvs(List<CustomerAmountSrv> customerAmountSrvs) {
        this.customerAmountSrvs = customerAmountSrvs;
    }

    public SettlementRequestSrv currency(CurrencySrv currency) {
        this.currency = currency;
        return this;
    }

    /**
     * Get currency
     *
     * @return currency
     **/

    public CurrencySrv getCurrency() {
        return currency;
    }

    public void setCurrency(CurrencySrv currency) {
        this.currency = currency;
    }

    public SettlementRequestSrv toolCode(String toolCode) {
        this.toolCode = toolCode;
        return this;
    }

    /**
     * Get toolCode
     *
     * @return toolCode
     **/

    public String getToolCode() {
        return toolCode;
    }

    public void setToolCode(String toolCode) {
        this.toolCode = toolCode;
    }

    public SettlementRequestSrv toolId(String toolId) {
        this.toolId = toolId;
        return this;
    }

    /**
     * Get toolId
     *
     * @return toolId
     **/

    public String getToolId() {
        return toolId;
    }

    public void setToolId(String toolId) {
        this.toolId = toolId;
    }

    public SettlementRequestSrv settlementLogSrvs(List<SettlementLogSrv> settlementLogSrvs) {
        this.settlementLogSrvs = settlementLogSrvs;
        return this;
    }

    public SettlementRequestSrv addSettlementLogSrvsItem(SettlementLogSrv settlementLogSrvsItem) {
        if (this.settlementLogSrvs == null) {
            this.settlementLogSrvs = new ArrayList<SettlementLogSrv>();
        }
        this.settlementLogSrvs.add(settlementLogSrvsItem);
        return this;
    }

    /**
     * Get settlementLogSrvs
     *
     * @return settlementLogSrvs
     **/

    public List<SettlementLogSrv> getSettlementLogSrvs() {
        return settlementLogSrvs;
    }

    public void setSettlementLogSrvs(List<SettlementLogSrv> settlementLogSrvs) {
        this.settlementLogSrvs = settlementLogSrvs;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SettlementRequestSrv settlementRequestSrv = (SettlementRequestSrv) o;
        return Objects.equals(this.id, settlementRequestSrv.id) &&
                Objects.equals(this.amount, settlementRequestSrv.amount) &&
                Objects.equals(this.requestDate, settlementRequestSrv.requestDate) &&
                Objects.equals(this.customerProfileSrv, settlementRequestSrv.customerProfileSrv) &&
                Objects.equals(this.settleDate, settlementRequestSrv.settleDate) &&
                Objects.equals(this.status, settlementRequestSrv.status) &&
                Objects.equals(this.customerAmountSrvs, settlementRequestSrv.customerAmountSrvs) &&
                Objects.equals(this.currency, settlementRequestSrv.currency) &&
                Objects.equals(this.toolCode, settlementRequestSrv.toolCode) &&
                Objects.equals(this.toolId, settlementRequestSrv.toolId) &&
                Objects.equals(this.settlementLogSrvs, settlementRequestSrv.settlementLogSrvs);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, amount, requestDate, customerProfileSrv, settleDate, status, customerAmountSrvs, currency, toolCode, toolId, settlementLogSrvs);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SettlementRequestSrv {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
        sb.append("    requestDate: ").append(toIndentedString(requestDate)).append("\n");
        sb.append("    customerProfileSrv: ").append(toIndentedString(customerProfileSrv)).append("\n");
        sb.append("    settleDate: ").append(toIndentedString(settleDate)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    customerAmountSrvs: ").append(toIndentedString(customerAmountSrvs)).append("\n");
        sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
        sb.append("    toolCode: ").append(toIndentedString(toolCode)).append("\n");
        sb.append("    toolId: ").append(toIndentedString(toolId)).append("\n");
        sb.append("    settlementLogSrvs: ").append(toIndentedString(settlementLogSrvs)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

