/*
 * Fanapium Core API
 * Fanapium B2B2C services
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.springframework.social.fanapium.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * SubProductSrv
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-02T09:35:11.370+04:30")
public class SubProductSrv {
    @JsonProperty("id")
    private Long id = null;

    @JsonProperty("previewInfo")
    private ImageInfoSrv previewInfo = null;

    @JsonProperty("availableCount")
    private Integer availableCount = null;

    @JsonProperty("price")
    private Long price = null;

    @JsonProperty("discount")
    private Long discount = null;

    @JsonProperty("attributeValues")
    private List<AttributeValueSrv> attributeValues = null;

    public SubProductSrv id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public SubProductSrv previewInfo(ImageInfoSrv previewInfo) {
        this.previewInfo = previewInfo;
        return this;
    }

    /**
     * Get previewInfo
     *
     * @return previewInfo
     **/

    public ImageInfoSrv getPreviewInfo() {
        return previewInfo;
    }

    public void setPreviewInfo(ImageInfoSrv previewInfo) {
        this.previewInfo = previewInfo;
    }

    public SubProductSrv availableCount(Integer availableCount) {
        this.availableCount = availableCount;
        return this;
    }

    /**
     * Get availableCount
     *
     * @return availableCount
     **/

    public Integer getAvailableCount() {
        return availableCount;
    }

    public void setAvailableCount(Integer availableCount) {
        this.availableCount = availableCount;
    }

    public SubProductSrv price(Long price) {
        this.price = price;
        return this;
    }

    /**
     * Get price
     *
     * @return price
     **/

    public Long getPrice() {
        return price;
    }

    public void setPrice(Long price) {
        this.price = price;
    }

    public SubProductSrv discount(Long discount) {
        this.discount = discount;
        return this;
    }

    /**
     * Get discount
     *
     * @return discount
     **/

    public Long getDiscount() {
        return discount;
    }

    public void setDiscount(Long discount) {
        this.discount = discount;
    }

    public SubProductSrv attributeValues(List<AttributeValueSrv> attributeValues) {
        this.attributeValues = attributeValues;
        return this;
    }

    public SubProductSrv addAttributeValuesItem(AttributeValueSrv attributeValuesItem) {
        if (this.attributeValues == null) {
            this.attributeValues = new ArrayList<AttributeValueSrv>();
        }
        this.attributeValues.add(attributeValuesItem);
        return this;
    }

    /**
     * Get attributeValues
     *
     * @return attributeValues
     **/

    public List<AttributeValueSrv> getAttributeValues() {
        return attributeValues;
    }

    public void setAttributeValues(List<AttributeValueSrv> attributeValues) {
        this.attributeValues = attributeValues;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SubProductSrv subProductSrv = (SubProductSrv) o;
        return Objects.equals(this.id, subProductSrv.id) &&
                Objects.equals(this.previewInfo, subProductSrv.previewInfo) &&
                Objects.equals(this.availableCount, subProductSrv.availableCount) &&
                Objects.equals(this.price, subProductSrv.price) &&
                Objects.equals(this.discount, subProductSrv.discount) &&
                Objects.equals(this.attributeValues, subProductSrv.attributeValues);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, previewInfo, availableCount, price, discount, attributeValues);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SubProductSrv {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    previewInfo: ").append(toIndentedString(previewInfo)).append("\n");
        sb.append("    availableCount: ").append(toIndentedString(availableCount)).append("\n");
        sb.append("    price: ").append(toIndentedString(price)).append("\n");
        sb.append("    discount: ").append(toIndentedString(discount)).append("\n");
        sb.append("    attributeValues: ").append(toIndentedString(attributeValues)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

