/*
 * Fanapium Core API
 * Fanapium B2B2C services
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.springframework.social.fanapium.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;

/**
 * TimelineItemSrv
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-02T09:35:11.370+04:30")
public class TimelineItemSrv {
    @JsonProperty("type")
    private Integer type = null;

    @JsonProperty("item")
    private ItemSrv item = null;

    public TimelineItemSrv type(Integer type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     **/

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public TimelineItemSrv item(ItemSrv item) {
        this.item = item;
        return this;
    }

    /**
     * Get item
     *
     * @return item
     **/

    public ItemSrv getItem() {
        return item;
    }

    public void setItem(ItemSrv item) {
        this.item = item;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TimelineItemSrv timelineItemSrv = (TimelineItemSrv) o;
        return Objects.equals(this.type, timelineItemSrv.type) &&
                Objects.equals(this.item, timelineItemSrv.item);
    }

    @Override
    public int hashCode() {
        return Objects.hash(type, item);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TimelineItemSrv {\n");

        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    item: ").append(toIndentedString(item)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

