/*
 * Fanapium Core API
 * Fanapium B2B2C services
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.springframework.social.fanapium.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Objects;

/**
 * UserPostInfoSrv
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-02T09:35:11.370+04:30")
public class UserPostInfoSrv {
    @JsonProperty("postId")
    private Long postId = null;

    @JsonProperty("liked")
    private Boolean liked = null;

    @JsonProperty("favorite")
    private Boolean favorite = null;

    public UserPostInfoSrv postId(Long postId) {
        this.postId = postId;
        return this;
    }

    /**
     * Get postId
     *
     * @return postId
     **/

    public Long getPostId() {
        return postId;
    }

    public void setPostId(Long postId) {
        this.postId = postId;
    }

    public UserPostInfoSrv liked(Boolean liked) {
        this.liked = liked;
        return this;
    }

    /**
     * Get liked
     *
     * @return liked
     **/

    public Boolean isLiked() {
        return liked;
    }

    public void setLiked(Boolean liked) {
        this.liked = liked;
    }

    public UserPostInfoSrv favorite(Boolean favorite) {
        this.favorite = favorite;
        return this;
    }

    /**
     * Get favorite
     *
     * @return favorite
     **/

    public Boolean isFavorite() {
        return favorite;
    }

    public void setFavorite(Boolean favorite) {
        this.favorite = favorite;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UserPostInfoSrv userPostInfoSrv = (UserPostInfoSrv) o;
        return Objects.equals(this.postId, userPostInfoSrv.postId) &&
                Objects.equals(this.liked, userPostInfoSrv.liked) &&
                Objects.equals(this.favorite, userPostInfoSrv.favorite);
    }

    @Override
    public int hashCode() {
        return Objects.hash(postId, liked, favorite);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UserPostInfoSrv {\n");

        sb.append("    postId: ").append(toIndentedString(postId)).append("\n");
        sb.append("    liked: ").append(toIndentedString(liked)).append("\n");
        sb.append("    favorite: ").append(toIndentedString(favorite)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

