/*
 * Fanapium Core API
 * Fanapium B2B2C services
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.springframework.social.fanapium.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * UserAmountSrv
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-02T09:35:11.370+04:30")
public class UserAmountSrv {
    @JsonProperty("customerAmountSrvs")
    private List<CustomerAmountSrv> customerAmountSrvs = null;

    @JsonProperty("mainBusinessAmountSrvs")
    private List<BusinessAmountSrv> mainBusinessAmountSrvs = null;

    @JsonProperty("blockedBusinessAmountSrvs")
    private List<BusinessAmountSrv> blockedBusinessAmountSrvs = null;

    public UserAmountSrv customerAmountSrvs(List<CustomerAmountSrv> customerAmountSrvs) {
        this.customerAmountSrvs = customerAmountSrvs;
        return this;
    }

    public UserAmountSrv addCustomerAmountSrvsItem(CustomerAmountSrv customerAmountSrvsItem) {
        if (this.customerAmountSrvs == null) {
            this.customerAmountSrvs = new ArrayList<CustomerAmountSrv>();
        }
        this.customerAmountSrvs.add(customerAmountSrvsItem);
        return this;
    }

    /**
     * Get customerAmountSrvs
     *
     * @return customerAmountSrvs
     **/

    public List<CustomerAmountSrv> getCustomerAmountSrvs() {
        return customerAmountSrvs;
    }

    public void setCustomerAmountSrvs(List<CustomerAmountSrv> customerAmountSrvs) {
        this.customerAmountSrvs = customerAmountSrvs;
    }

    public UserAmountSrv mainBusinessAmountSrvs(List<BusinessAmountSrv> mainBusinessAmountSrvs) {
        this.mainBusinessAmountSrvs = mainBusinessAmountSrvs;
        return this;
    }

    public UserAmountSrv addMainBusinessAmountSrvsItem(BusinessAmountSrv mainBusinessAmountSrvsItem) {
        if (this.mainBusinessAmountSrvs == null) {
            this.mainBusinessAmountSrvs = new ArrayList<BusinessAmountSrv>();
        }
        this.mainBusinessAmountSrvs.add(mainBusinessAmountSrvsItem);
        return this;
    }

    /**
     * Get mainBusinessAmountSrvs
     *
     * @return mainBusinessAmountSrvs
     **/

    public List<BusinessAmountSrv> getMainBusinessAmountSrvs() {
        return mainBusinessAmountSrvs;
    }

    public void setMainBusinessAmountSrvs(List<BusinessAmountSrv> mainBusinessAmountSrvs) {
        this.mainBusinessAmountSrvs = mainBusinessAmountSrvs;
    }

    public UserAmountSrv blockedBusinessAmountSrvs(List<BusinessAmountSrv> blockedBusinessAmountSrvs) {
        this.blockedBusinessAmountSrvs = blockedBusinessAmountSrvs;
        return this;
    }

    public UserAmountSrv addBlockedBusinessAmountSrvsItem(BusinessAmountSrv blockedBusinessAmountSrvsItem) {
        if (this.blockedBusinessAmountSrvs == null) {
            this.blockedBusinessAmountSrvs = new ArrayList<BusinessAmountSrv>();
        }
        this.blockedBusinessAmountSrvs.add(blockedBusinessAmountSrvsItem);
        return this;
    }

    /**
     * Get blockedBusinessAmountSrvs
     *
     * @return blockedBusinessAmountSrvs
     **/

    public List<BusinessAmountSrv> getBlockedBusinessAmountSrvs() {
        return blockedBusinessAmountSrvs;
    }

    public void setBlockedBusinessAmountSrvs(List<BusinessAmountSrv> blockedBusinessAmountSrvs) {
        this.blockedBusinessAmountSrvs = blockedBusinessAmountSrvs;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UserAmountSrv userAmountSrv = (UserAmountSrv) o;
        return Objects.equals(this.customerAmountSrvs, userAmountSrv.customerAmountSrvs) &&
                Objects.equals(this.mainBusinessAmountSrvs, userAmountSrv.mainBusinessAmountSrvs) &&
                Objects.equals(this.blockedBusinessAmountSrvs, userAmountSrv.blockedBusinessAmountSrvs);
    }

    @Override
    public int hashCode() {
        return Objects.hash(customerAmountSrvs, mainBusinessAmountSrvs, blockedBusinessAmountSrvs);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UserAmountSrv {\n");

        sb.append("    customerAmountSrvs: ").append(toIndentedString(customerAmountSrvs)).append("\n");
        sb.append("    mainBusinessAmountSrvs: ").append(toIndentedString(mainBusinessAmountSrvs)).append("\n");
        sb.append("    blockedBusinessAmountSrvs: ").append(toIndentedString(blockedBusinessAmountSrvs)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

