/*
 * Fanapium Core API
 * Fanapium B2B2C services
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.springframework.social.fanapium.api.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * VoucherSrv
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-02T09:35:11.370+04:30")
public class VoucherSrv {
    @JsonProperty("id")
    private Long id = null;

    @JsonProperty("active")
    private Boolean active = null;

    @JsonProperty("business")
    private BusinessSoftSrv business = null;

    @JsonProperty("guild")
    private GuildSrv guild = null;

    @JsonProperty("limitedConsumer")
    private UserSrv limitedConsumer = null;

    @JsonProperty("consumer")
    private UserSrv consumer = null;

    @JsonProperty("hash")
    private String hash = null;

    @JsonProperty("name")
    private String name = null;

    @JsonProperty("description")
    private String description = null;

    @JsonProperty("creditAmount")
    private Double creditAmount = null;

    @JsonProperty("discountPercentage")
    private Float discountPercentage = null;

    @JsonProperty("creationDate")
    private Long creationDate = null;

    @JsonProperty("expireDate")
    private Long expireDate = null;

    @JsonProperty("productList")
    private List<ProductSrv> productList = null;

    @JsonProperty("usedAmount")
    private Double usedAmount = null;

    @JsonProperty("type")
    private Integer type = null;

    @JsonProperty("usageList")
    private List<VoucherUsageSrv> usageList = null;

    @JsonProperty("used")
    private Boolean used = null;

    public VoucherSrv id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public VoucherSrv active(Boolean active) {
        this.active = active;
        return this;
    }

    /**
     * Get active
     *
     * @return active
     **/

    public Boolean isActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public VoucherSrv business(BusinessSoftSrv business) {
        this.business = business;
        return this;
    }

    /**
     * Get business
     *
     * @return business
     **/

    public BusinessSoftSrv getBusiness() {
        return business;
    }

    public void setBusiness(BusinessSoftSrv business) {
        this.business = business;
    }

    public VoucherSrv guild(GuildSrv guild) {
        this.guild = guild;
        return this;
    }

    /**
     * Get guild
     *
     * @return guild
     **/

    public GuildSrv getGuild() {
        return guild;
    }

    public void setGuild(GuildSrv guild) {
        this.guild = guild;
    }

    public VoucherSrv limitedConsumer(UserSrv limitedConsumer) {
        this.limitedConsumer = limitedConsumer;
        return this;
    }

    /**
     * Get limitedConsumer
     *
     * @return limitedConsumer
     **/

    public UserSrv getLimitedConsumer() {
        return limitedConsumer;
    }

    public void setLimitedConsumer(UserSrv limitedConsumer) {
        this.limitedConsumer = limitedConsumer;
    }

    public VoucherSrv consumer(UserSrv consumer) {
        this.consumer = consumer;
        return this;
    }

    /**
     * Get consumer
     *
     * @return consumer
     **/

    public UserSrv getConsumer() {
        return consumer;
    }

    public void setConsumer(UserSrv consumer) {
        this.consumer = consumer;
    }

    public VoucherSrv hash(String hash) {
        this.hash = hash;
        return this;
    }

    /**
     * Get hash
     *
     * @return hash
     **/

    public String getHash() {
        return hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }

    public VoucherSrv name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public VoucherSrv description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get description
     *
     * @return description
     **/

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public VoucherSrv creditAmount(Double creditAmount) {
        this.creditAmount = creditAmount;
        return this;
    }

    /**
     * Get creditAmount
     *
     * @return creditAmount
     **/

    public Double getCreditAmount() {
        return creditAmount;
    }

    public void setCreditAmount(Double creditAmount) {
        this.creditAmount = creditAmount;
    }

    public VoucherSrv discountPercentage(Float discountPercentage) {
        this.discountPercentage = discountPercentage;
        return this;
    }

    /**
     * Get discountPercentage
     *
     * @return discountPercentage
     **/

    public Float getDiscountPercentage() {
        return discountPercentage;
    }

    public void setDiscountPercentage(Float discountPercentage) {
        this.discountPercentage = discountPercentage;
    }

    public VoucherSrv creationDate(Long creationDate) {
        this.creationDate = creationDate;
        return this;
    }

    /**
     * Get creationDate
     *
     * @return creationDate
     **/

    public Long getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Long creationDate) {
        this.creationDate = creationDate;
    }

    public VoucherSrv expireDate(Long expireDate) {
        this.expireDate = expireDate;
        return this;
    }

    /**
     * Get expireDate
     *
     * @return expireDate
     **/

    public Long getExpireDate() {
        return expireDate;
    }

    public void setExpireDate(Long expireDate) {
        this.expireDate = expireDate;
    }

    public VoucherSrv productList(List<ProductSrv> productList) {
        this.productList = productList;
        return this;
    }

    public VoucherSrv addProductListItem(ProductSrv productListItem) {
        if (this.productList == null) {
            this.productList = new ArrayList<ProductSrv>();
        }
        this.productList.add(productListItem);
        return this;
    }

    /**
     * Get productList
     *
     * @return productList
     **/

    public List<ProductSrv> getProductList() {
        return productList;
    }

    public void setProductList(List<ProductSrv> productList) {
        this.productList = productList;
    }

    public VoucherSrv usedAmount(Double usedAmount) {
        this.usedAmount = usedAmount;
        return this;
    }

    /**
     * Get usedAmount
     *
     * @return usedAmount
     **/

    public Double getUsedAmount() {
        return usedAmount;
    }

    public void setUsedAmount(Double usedAmount) {
        this.usedAmount = usedAmount;
    }

    public VoucherSrv type(Integer type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     **/

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public VoucherSrv usageList(List<VoucherUsageSrv> usageList) {
        this.usageList = usageList;
        return this;
    }

    public VoucherSrv addUsageListItem(VoucherUsageSrv usageListItem) {
        if (this.usageList == null) {
            this.usageList = new ArrayList<VoucherUsageSrv>();
        }
        this.usageList.add(usageListItem);
        return this;
    }

    /**
     * Get usageList
     *
     * @return usageList
     **/

    public List<VoucherUsageSrv> getUsageList() {
        return usageList;
    }

    public void setUsageList(List<VoucherUsageSrv> usageList) {
        this.usageList = usageList;
    }

    public VoucherSrv used(Boolean used) {
        this.used = used;
        return this;
    }

    /**
     * Get used
     *
     * @return used
     **/

    public Boolean isUsed() {
        return used;
    }

    public void setUsed(Boolean used) {
        this.used = used;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VoucherSrv voucherSrv = (VoucherSrv) o;
        return Objects.equals(this.id, voucherSrv.id) &&
                Objects.equals(this.active, voucherSrv.active) &&
                Objects.equals(this.business, voucherSrv.business) &&
                Objects.equals(this.guild, voucherSrv.guild) &&
                Objects.equals(this.limitedConsumer, voucherSrv.limitedConsumer) &&
                Objects.equals(this.consumer, voucherSrv.consumer) &&
                Objects.equals(this.hash, voucherSrv.hash) &&
                Objects.equals(this.name, voucherSrv.name) &&
                Objects.equals(this.description, voucherSrv.description) &&
                Objects.equals(this.creditAmount, voucherSrv.creditAmount) &&
                Objects.equals(this.discountPercentage, voucherSrv.discountPercentage) &&
                Objects.equals(this.creationDate, voucherSrv.creationDate) &&
                Objects.equals(this.expireDate, voucherSrv.expireDate) &&
                Objects.equals(this.productList, voucherSrv.productList) &&
                Objects.equals(this.usedAmount, voucherSrv.usedAmount) &&
                Objects.equals(this.type, voucherSrv.type) &&
                Objects.equals(this.usageList, voucherSrv.usageList) &&
                Objects.equals(this.used, voucherSrv.used);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, active, business, guild, limitedConsumer, consumer, hash, name, description, creditAmount, discountPercentage, creationDate, expireDate, productList, usedAmount, type, usageList, used);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class VoucherSrv {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    active: ").append(toIndentedString(active)).append("\n");
        sb.append("    business: ").append(toIndentedString(business)).append("\n");
        sb.append("    guild: ").append(toIndentedString(guild)).append("\n");
        sb.append("    limitedConsumer: ").append(toIndentedString(limitedConsumer)).append("\n");
        sb.append("    consumer: ").append(toIndentedString(consumer)).append("\n");
        sb.append("    hash: ").append(toIndentedString(hash)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    creditAmount: ").append(toIndentedString(creditAmount)).append("\n");
        sb.append("    discountPercentage: ").append(toIndentedString(discountPercentage)).append("\n");
        sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
        sb.append("    expireDate: ").append(toIndentedString(expireDate)).append("\n");
        sb.append("    productList: ").append(toIndentedString(productList)).append("\n");
        sb.append("    usedAmount: ").append(toIndentedString(usedAmount)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    usageList: ").append(toIndentedString(usageList)).append("\n");
        sb.append("    used: ").append(toIndentedString(used)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

